# Site settings
title: Blog #website title
description: > # this means to ignore newlines until "baseurl:"
  Blog
url: https://zar67.github.io # the base hostname & protocol for your site
baseurl: /LLP-the-shining #the sub-path of your site, e.g. /blog/

disqus_shortname:  # leave empty if you don't want comments
google_analytics: false #if set to "true" modify the google_analytycs.html, set to false otherwise

# Links settings
links:
  - name:         Home
    url:          /
  - name:         Archive
    url:          /archive
    external:     false
  - name:         GitHub
    url:          https://github.com/zar67
    external:     true

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
